name: CI - gs-env

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/env/**'
      - 'src/schemas/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci-env.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/env/**'
      - 'src/schemas/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci-env.yml'

env:
  UV_CACHE_DIR: ~/.cache/uv

jobs:
  # Lint, type check, and build gs-env
  ci:
    name: CI gs-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-env-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-env-
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv sync --dev

      - name: Run ruff linting on gs-env
        run: uv run ruff check src/env/

      - name: Run ruff formatting check on gs-env
        run: uv run ruff format --check src/env/

      - name: Run pyright type checking on gs-env
        run: |
          cd src/env
          uv run pyright

      - name: Build gs-env package
        run: |
          cd src/env
          uv build

      - name: Validate package structure
        run: |
          # Check that built package exists
          ls -la src/env/dist/
          # Validate package metadata
          uv run python -c "
          import tomllib
          with open('src/env/pyproject.toml', 'rb') as f:
              config = tomllib.load(f)
          print('gs-env package config:', config['project']['name'])
          "

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gs-env-dist
          path: src/env/dist/
          retention-days: 7
