name: CI (gs-env)

on:
  push:
    paths:
      - "src/env/**"
      - "src/schemas/**"   # rebuild if dependency changed
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/ci-env.yml"
  pull_request:
    paths:
      - "src/env/**"
      - "src/schemas/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/ci-env.yml"

jobs:
  build-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: src/env

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - name: Cache venv & uv wheels
        uses: actions/cache@v4
        with:
          path: |
            src/env/.venv
            ~/.cache/uv
          key: ${{ runner.os }}-py312-env-${{ hashFiles('uv.lock', 'src/env/pyproject.toml', 'src/schemas/pyproject.toml') }}

      - run: uv venv --python 3.12
      - run: uv pip install hatchling

      # install schemas first, then env
      - run: |
          pushd ../schemas
          uv pip install -e . --no-build-isolation
          popd
          uv pip install -e . --no-build-isolation

      - run: uv pip install pytest ruff pyright

      - run: uvx ruff check . --output-format=github
      - run: uvx pyright -p .
      - run: uv run python -m pytest -q || ([ $? -eq 5 ] && exit 0)
q