name: CI (gs-schemas)

on:
  push:
    paths:
      - "src/schemas/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/ci-schemas.yml"
  pull_request:
    paths:
      - "src/schemas/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/ci-schemas.yml"

jobs:
  schemas:
    uses: ./.github/workflows/python-package.yml
    with:
      os: ubuntu-24.04
      package_dir: src/schemas
      package_name: gs-schemas
    secrets: inherit
